# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: false }
  allowed_methods_listener: true
  access_denied_listener:
    json: true
  body_listener:
    decoders:
      json: fos_rest.decoder.json
