framework:
    messenger:
        transport:
            serializer: true
        transports:
            amqp: "%env(MESSENGER_TRANSPORT_DSN)%"
        routing:
            'App\Message\NewUserMessage':  amqp
